
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

import views.inicio_view

from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/body_measurements_view")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_body_measurements():

    window = Tk()

    window.geometry("1280x832")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 832,
        width = 1280,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        203.0,
        277.0,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        515.0,
        278.0,
        image=image_image_2
    )

    canvas.create_rectangle(
        151.0,
        484.0,
        583.0,
        711.0,
        fill="#DAD3EE",
        outline="")

    canvas.create_text(
        233.0,
        510.0,
        anchor="nw",
        text="Body Mass Index (IBM)",
        fill="#000000",
        font=("Mulish SemiBold", 25 * -1)
    )

    canvas.create_text(
        201.0,
        597.0,
        anchor="nw",
        text="24.5",
        fill="#000000",
        font=("Mulish SemiBold", 25 * -1)
    )

    image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_3 = canvas.create_image(
        420.0,
        652.0,
        image=image_image_3
    )

    image_image_4 = PhotoImage(
        file=relative_to_assets("image_4.png"))
    image_4 = canvas.create_image(
        964.0,
        484.0,
        image=image_image_4
    )

    canvas.create_rectangle(
        0.0,
        0.0,
        1280.0,
        160.0,
        fill="#EDECF4",
        outline="")

    image_image_5 = PhotoImage(
        file=relative_to_assets("image_5.png"))
    image_5 = canvas.create_image(
        1064.0,
        59.0,
        image=image_image_5
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: window.destroy() or views.inicio_view.open_incio_view(),
        relief="flat"
    )
    button_1.place(
        x=1103.0,
        y=102.0,
        width=67.0,
        height=29.0
    )

    image_image_6 = PhotoImage(
        file=relative_to_assets("image_6.png"))
    image_6 = canvas.create_image(
        152.0,
        256.0,
        image=image_image_6
    )

    image_image_7 = PhotoImage(
        file=relative_to_assets("image_7.png"))
    image_7 = canvas.create_image(
        454.0,
        256.0,
        image=image_image_7
    )

    canvas.create_text(
        1120.0,
        38.0,
        anchor="nw",
        text="Josue Tsai",
        fill="#000000",
        font=("Poppins Regular", 12 * -1)
    )

    canvas.create_text(
        1100.0,
        59.0,
        anchor="nw",
        text="josuetsai@gmail.com",
        fill="#000000",
        font=("Poppins Regular", 10 * -1)
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=113.0,
        y=398.0,
        width=183.0,
        height=45.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat"
    )
    button_3.place(
        x=419.0,
        y=398.0,
        width=183.0,
        height=45.0
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        204.0,
        332.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=150.0,
        y=316.0,
        width=108.0,
        height=30.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        529.0,
        332.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=475.0,
        y=316.0,
        width=108.0,
        height=30.0
    )
    window.resizable(False, False)
    window.mainloop()
